version: "3.5"
services:
  app:
    image: hpccbk/mlflow-base:3.2.1
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net
    volumes:
      - ./data:/data

networks:
  hadoop-net:
    external:
      name: confluent
